apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: hoboapplepay
  namespace: default
spec:
  rules:
    - host: '*.tcpci.com'
      http:
        paths:
          - path: /.well-known/apple-developer-merchantid-domain-association.txt
            backend:
              serviceName: hoboapplepay
              servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: hoboapplepay
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  type: NodePort
  selector:
    app: hoboapplepay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoboapplepay
  labels:
    app: hoboapplepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoboapplepay
  template:
    metadata:
      labels:
        app: hoboapplepay
    spec:
      imagePullSecrets:
        - name: tylerorg
      containers:
        - image: tylerorg/hoboapplepay:1.0.3
          name: hoboapplepay
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 200m